/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@packet.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BgpConfigRequestInput {
    #[serde(rename = "deployment_type")]
    pub deployment_type: String,
    #[serde(rename = "asn")]
    pub asn: i32,
    #[serde(rename = "md5", skip_serializing_if = "Option::is_none")]
    pub md5: Option<String>,
    #[serde(rename = "use_case", skip_serializing_if = "Option::is_none")]
    pub use_case: Option<String>,
}

impl BgpConfigRequestInput {
    pub fn new(deployment_type: String, asn: i32) -> BgpConfigRequestInput {
        BgpConfigRequestInput {
            deployment_type,
            asn,
            md5: None,
            use_case: None,
        }
    }
}


