/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@packet.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Entitlement {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "weight")]
    pub weight: i32,
    #[serde(rename = "instance_quota", skip_serializing_if = "Option::is_none")]
    pub instance_quota: Option<serde_json::Value>,
    #[serde(rename = "project_quota", skip_serializing_if = "Option::is_none")]
    pub project_quota: Option<i32>,
    #[serde(rename = "volume_quota", skip_serializing_if = "Option::is_none")]
    pub volume_quota: Option<serde_json::Value>,
    #[serde(rename = "ip_quota", skip_serializing_if = "Option::is_none")]
    pub ip_quota: Option<serde_json::Value>,
    #[serde(rename = "feature_access", skip_serializing_if = "Option::is_none")]
    pub feature_access: Option<serde_json::Value>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "volume_limits", skip_serializing_if = "Option::is_none")]
    pub volume_limits: Option<serde_json::Value>,
}

impl Entitlement {
    pub fn new(id: String, slug: String, weight: i32) -> Entitlement {
        Entitlement {
            id,
            description: None,
            slug,
            name: None,
            weight,
            instance_quota: None,
            project_quota: None,
            volume_quota: None,
            ip_quota: None,
            feature_access: None,
            href: None,
            volume_limits: None,
        }
    }
}


