/*
 * Metal API
 *
 * This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterconnectionList {
    #[serde(rename = "interconnections", skip_serializing_if = "Option::is_none")]
    pub interconnections: Option<Vec<crate::models::Interconnection>>,
}

impl InterconnectionList {
    pub fn new() -> InterconnectionList {
        InterconnectionList {
            interconnections: None,
        }
    }
}


