/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@packet.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpAddressInput {
    /// Address Family for IP Address
    #[serde(rename = "address_family", skip_serializing_if = "Option::is_none")]
    pub address_family: Option<f32>,
}

impl IpAddressInput {
    pub fn new() -> IpAddressInput {
        IpAddressInput {
            address_family: None,
        }
    }
}


