/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@packet.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpReservationRequestInput {
    #[serde(rename = "type")]
    pub _type: String,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "facility", skip_serializing_if = "Option::is_none")]
    pub facility: Option<String>,
    #[serde(rename = "customdata", skip_serializing_if = "Option::is_none")]
    pub customdata: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "fail_on_approval_required", skip_serializing_if = "Option::is_none")]
    pub fail_on_approval_required: Option<bool>,
}

impl IpReservationRequestInput {
    pub fn new(_type: String, quantity: i32) -> IpReservationRequestInput {
        IpReservationRequestInput {
            _type,
            quantity,
            comments: None,
            facility: None,
            customdata: None,
            tags: None,
            details: None,
            fail_on_approval_required: None,
        }
    }
}


