/*
 * Metal API
 *
 * This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMethodBillingAddress {
    #[serde(rename = "street_address", skip_serializing_if = "Option::is_none")]
    pub street_address: Option<String>,
    #[serde(rename = "postal_code", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    #[serde(rename = "country_code_alpha2", skip_serializing_if = "Option::is_none")]
    pub country_code_alpha2: Option<String>,
}

impl PaymentMethodBillingAddress {
    pub fn new() -> PaymentMethodBillingAddress {
        PaymentMethodBillingAddress {
            street_address: None,
            postal_code: None,
            country_code_alpha2: None,
        }
    }
}


