/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@packet.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectUpdateInput {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "payment_method_id", skip_serializing_if = "Option::is_none")]
    pub payment_method_id: Option<String>,
    #[serde(rename = "backend_transfer_enabled", skip_serializing_if = "Option::is_none")]
    pub backend_transfer_enabled: Option<bool>,
    #[serde(rename = "customdata", skip_serializing_if = "Option::is_none")]
    pub customdata: Option<String>,
}

impl ProjectUpdateInput {
    pub fn new() -> ProjectUpdateInput {
        ProjectUpdateInput {
            name: None,
            payment_method_id: None,
            backend_transfer_enabled: None,
            customdata: None,
        }
    }
}


