/*
 * Metal API
 *
 * This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecoveryCodeList {
    #[serde(rename = "recovery_codes", skip_serializing_if = "Option::is_none")]
    pub recovery_codes: Option<Vec<String>>,
}

impl RecoveryCodeList {
    pub fn new() -> RecoveryCodeList {
        RecoveryCodeList {
            recovery_codes: None,
        }
    }
}


