/*
 * Metal API
 *
 * This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpotMarketRequestCreateInputInstanceAttributes {
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<String>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "hostnames", skip_serializing_if = "Option::is_none")]
    pub hostnames: Option<Vec<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "billing_cycle", skip_serializing_if = "Option::is_none")]
    pub billing_cycle: Option<String>,
    #[serde(rename = "operating_system", skip_serializing_if = "Option::is_none")]
    pub operating_system: Option<String>,
    #[serde(rename = "always_pxe", skip_serializing_if = "Option::is_none")]
    pub always_pxe: Option<bool>,
    #[serde(rename = "userdata", skip_serializing_if = "Option::is_none")]
    pub userdata: Option<String>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "termination_time", skip_serializing_if = "Option::is_none")]
    pub termination_time: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "project_ssh_keys", skip_serializing_if = "Option::is_none")]
    pub project_ssh_keys: Option<Vec<String>>,
    #[serde(rename = "user_ssh_keys", skip_serializing_if = "Option::is_none")]
    pub user_ssh_keys: Option<Vec<String>>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
    #[serde(rename = "customdata", skip_serializing_if = "Option::is_none")]
    pub customdata: Option<String>,
    #[serde(rename = "public_ipv4_subnet_size", skip_serializing_if = "Option::is_none")]
    pub public_ipv4_subnet_size: Option<i32>,
    #[serde(rename = "private_ipv4_subnet_size", skip_serializing_if = "Option::is_none")]
    pub private_ipv4_subnet_size: Option<i32>,
}

impl SpotMarketRequestCreateInputInstanceAttributes {
    pub fn new() -> SpotMarketRequestCreateInputInstanceAttributes {
        SpotMarketRequestCreateInputInstanceAttributes {
            plan: None,
            hostname: None,
            hostnames: None,
            description: None,
            billing_cycle: None,
            operating_system: None,
            always_pxe: None,
            userdata: None,
            locked: None,
            termination_time: None,
            tags: None,
            project_ssh_keys: None,
            user_ssh_keys: None,
            features: None,
            customdata: None,
            public_ipv4_subnet_size: None,
            private_ipv4_subnet_size: None,
        }
    }
}


