/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@packet.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportRequestInput {
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "device_id", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
}

impl SupportRequestInput {
    pub fn new(subject: String, message: String) -> SupportRequestInput {
        SupportRequestInput {
            subject,
            message,
            project_id: None,
            device_id: None,
        }
    }
}


