/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@packet.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VirtualNetworkCreateInput {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "facility", skip_serializing_if = "Option::is_none")]
    pub facility: Option<String>,
    #[serde(rename = "vxlan", skip_serializing_if = "Option::is_none")]
    pub vxlan: Option<i32>,
    #[serde(rename = "vlan", skip_serializing_if = "Option::is_none")]
    pub vlan: Option<i32>,
}

impl VirtualNetworkCreateInput {
    pub fn new() -> VirtualNetworkCreateInput {
        VirtualNetworkCreateInput {
            project_id: None,
            description: None,
            facility: None,
            vxlan: None,
            vlan: None,
        }
    }
}


