/*
 * Metal API
 *
 * This is the API for Equinix Metal Product. Interact with your devices, user account, and projects.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VolumeCreateInput {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// ams1, ewr1, nrt1, sjc1
    #[serde(rename = "facility")]
    pub facility: String,
    /// storage_1, storage_2
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    /// hourly
    #[serde(rename = "billing_cycle", skip_serializing_if = "Option::is_none")]
    pub billing_cycle: Option<String>,
    #[serde(rename = "snapshot_policies", skip_serializing_if = "Option::is_none")]
    pub snapshot_policies: Option<crate::models::SnapshotPolicyInput>,
    #[serde(rename = "customdata", skip_serializing_if = "Option::is_none")]
    pub customdata: Option<String>,
}

impl VolumeCreateInput {
    pub fn new(facility: String, plan: String, size: i32) -> VolumeCreateInput {
        VolumeCreateInput {
            description: None,
            facility,
            plan,
            size,
            locked: None,
            billing_cycle: None,
            snapshot_policies: None,
            customdata: None,
        }
    }
}


